# Generated by Django 3.1.2 on 2020-11-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': 'Localities'},
        ),
    ]
