# Generated by Django 3.1.2 on 2020-11-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='medical_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='medical.medicalagency'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='location.state'),
        ),
    ]
