# Generated by Django 3.1.2 on 2020-11-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemedicalofficer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to='location.state'),
        ),
        migrations.AddField(
            model_name='statemedicalofficer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to='account.user'),
        ),
        migrations.AddField(
            model_name='districtmedicalofficer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to='location.district'),
        ),
        migrations.AddField(
            model_name='districtmedicalofficer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to='account.user'),
        ),
    ]
