# Generated by Django 3.1.2 on 2020-11-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201109_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemedicalofficer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='statemedicalofficer',
            name='user',
        ),
        migrations.DeleteModel(
            name='DistrictMedicalOfficer',
        ),
        migrations.DeleteModel(
            name='StateMedicalOfficer',
        ),
    ]
