# Generated by Django 3.1.2 on 2020-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='days_offset',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
