# Generated by Django 3.1.2 on 2020-11-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_agencies', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_helpers', to='medical.medicalagency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_helpers', to='account.user')),
            ],
        ),
    ]
