# Generated by Django 3.1.2 on 2020-11-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_agencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Agencies',
            },
        ),
        migrations.CreateModel(
            name='StateMedicalOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to='location.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'State Medical Officers',
            },
        ),
        migrations.CreateModel(
            name='MedicalHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_helpers', to='medical.medicalagency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_helpers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Helpers',
            },
        ),
        migrations.CreateModel(
            name='DistrictMedicalOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to='location.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'District Medical Officers',
            },
        ),
    ]
