# Generated by Django 3.1.2 on 2020-11-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20201120_1905'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcarePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('process', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_policies', to='location.state')),
            ],
            options={
                'verbose_name_plural': 'Healthcare Policies',
            },
        ),
    ]
