# Generated by Django 3.1.2 on 2020-11-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201120_1551'),
        ('location', '0002_auto_20201120_1551'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalagency',
            options={'verbose_name_plural': 'Medical Agencies'},
        ),
        migrations.AlterModelOptions(
            name='medicalhelper',
            options={'verbose_name_plural': 'Medical Helpers'},
        ),
        migrations.CreateModel(
            name='StateMedicalOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to='location.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to='account.user')),
            ],
            options={
                'verbose_name_plural': 'State Medical Officers',
            },
        ),
        migrations.CreateModel(
            name='DistrictMedicalOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to='location.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to='account.user')),
            ],
            options={
                'verbose_name_plural': 'District Medical Officers',
            },
        ),
    ]
