# Generated by Django 3.1.2 on 2020-11-20 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0002_auto_20201120_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmedicalofficer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_medical_officers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalagency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_agencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalhelper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_helpers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statemedicalofficer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_medical_officers', to=settings.AUTH_USER_MODEL),
        ),
    ]
