# Generated by Django 3.1.2 on 2020-11-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='location.locality'),
        ),
        migrations.AddField(
            model_name='parent',
            name='medical_helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='medical.medicalhelper'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='beneficiary.parent'),
        ),
    ]
