# Generated by Django 3.1.2 on 2020-11-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('beneficiary', '0002_auto_20201120_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_vaccines', to='beneficiary.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_vaccines', to='data.vaccine')),
            ],
            options={
                'verbose_name_plural': 'Child Vaccines',
            },
        ),
    ]
