# Generated by Django 3.1.2 on 2020-11-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_childvaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('is_sent', models.BooleanField(default=False)),
                ('child_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='beneficiary.childvaccine')),
            ],
        ),
    ]
